version: '3'
services:
  web:
    image: docker-node-mongo
    build: ./ 
    command: npm start
    ports: 
      - "8080:8081"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - "mongo"

  mongo:
    image: "mongo"
    ports:
      - "27107:27107"

